# Generated by Django 3.0 on 2020-05-04 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=280)),
                ('image', models.URLField()),
                ('category', models.CharField(choices=[('JB', 'Jab'), ('RH', 'Right Hook')], default='JB', max_length=2)),
                ('pubdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
