# Generated by Django 3.0 on 2020-05-06 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200504_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pubdate', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('tags', models.TextField(blank=True, help_text="Separate tags with ','")),
                ('image', models.URLField(blank=True, help_text='Optional for post')),
            ],
        ),
    ]
