# Generated by Django 3.0 on 2020-05-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('BL', 'Blog Post'), ('YT', 'YouTube Description'), ('PC', 'Podcast Episode'), ('FB', 'Facebook Post')], default='BL', max_length=2),
        ),
    ]
