# Generated by Django 3.0 on 2020-05-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_post_outline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliatePlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('url', models.URLField()),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.AffiliateCategory')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.AffiliatePlatform')),
            ],
        ),
    ]
