# Generated by Django 3.0 on 2020-05-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_affiliatecategory_affiliatemarketing_affiliateplatform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffiliateMarketing',
            new_name='AffiliateProduct',
        ),
    ]
